[package]
name = "fuse-query"
version = "0.1.0"
description = "A Distributed Query Engine"
authors = ["BohuTANG <bohu@datafuse.dev>", "Peter <peter@datafuse.dev>", "Kevin <kevin@datafuse.dev>"]
license = "AGPL-3.0"
include = [
    "benches/*.rs",
    "src/**/*.rs",
    "Cargo.toml",
]
edition = "2018"

[[bin]]
name = "fuse-query"
path = "src/bin/fuse-query.rs"

[dependencies]
arrow = { git= "https://github.com/apache/arrow", features = ["simd"]}
async-trait = "0.1"
bincode = "1.3.1"
futures = "0.3"
lazy_static = "1.4.0"
log = "0.4"
msql-srv = "0.9"
num = "0.3"
num_cpus = "1.0"
paste = "^1.0"
serde_json = "1.0"
sqlparser = "0.6"
simplelog = "0.10"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
threadpool = "1.8.1"
tokio = { version = "1.0", features = ["macros", "rt", "rt-multi-thread", "signal", "sync"] }

[dev-dependencies]
criterion = "0.3"
pretty_assertions = "0.6"

[[bench]]
name = "bench_main"
harness = false

