[package]
name = "common-progress"
version = "0.1.0"
authors = ["Datafuse Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies] # In alphabetical order
# Workspace dependencies
common-infallible = {path = "../infallible"}

# Github dependencies

# Crates.io dependencies
anyhow = "1.0.57"

[dev-dependencies]
pretty_assertions = "0.7"
