[package]
name = "common-datablocks"
version = "0.1.0"
authors = ["Datafuse Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies] # In alphabetical order
# Workspace dependencies
common-arrow = {path = "../arrow"}
common-datavalues = {path = "../datavalues"}
common-exception = {path = "../exception"}

# Github dependencies

# Crates.io dependencies
anyhow = "1.0.53"
prettytable-rs = { version = "0.8.0"}
