[package]
name = "common-planners"
version = "0.1.0"
authors = ["Datafuse Authors <opensource@datafuselabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2018"

[dependencies] # In alphabetical order
# Workspace dependencies
common-datavalues = {path = "../datavalues"}
common-functions = {path = "../functions"}
common-exception = {path = "../exception"}

# Github dependencies

# Crates.io dependencies
anyhow = "1.0.44"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
pretty_assertions = "0.7"
